export class ClaimInterviewModel {
    id: number;
    city: string;
    state: string;
    zipcode: string;
    address: string;
    lausdFaxDate: string;
    bybClaimDate: string;
    effectiveDate: string;
    claimantName: string;
    socialSecurityNumber: string;
    status: string;
    date: string;
    time: string;
    detInterviewer: string;
    interviewerPhoneNumber: string;
    representativeName: string;
    phoneNumber: string;
    signature: string;
    title: string;
    representativeDate: string;
    issuesList: number;
    formCode: string;
    createdBy: string;
    modifiedBy: string;
    createdOn: string;
    modifiedOn: string;
    claimId: number;
}
