export class NewClaim {
    id                   : number;
    requestNumber        : number;
    type                 : string;
    requestTitle         : string;
    claimantName         : string;
    currentStage         : string;
    createdOn            : string;
    modifiedOn           : number;
    gender               : string;
    employeeNumber       : string;
    socialSecurityNumber : string;
    createdBy            : string;
    modifiedBy           : string;
    reasonForSeparation  : string;
    newClaim             : string;
    additionalClaim      : string;
    benefitYearBeginning : number;
    dateMailedToEDD      : string;
    mailDate             : string;
    effectiveDateOfClaim : string;
    lastDateWorked       : string;
    claimResponse        : string;
    claimInterview       : string;
    claimDetermination   : string;
    responsetoEmployer   : string;
    claimAppeal          : string;
    alJdecision          : string;
    acknowledgement      : string;
    wagesAfterAppeal     : string;
    additionalInformation: string;
}
