export class Wages {
    id                             : number;
    claimantName                   : string;
    socialSecurityNumber           : string;
    otherSSN                       : string;
    claimDate                      : string;
    fieldOfficePhoneNo             : string;
    fieldOfficeAddress             : string;
    notes                          : string;
    postmarkedResponseDate         : string;
    wagesReport                    : string;
    wagesQuarter1Date              : string;
    wagesQuarter2Date              : string;
    wagesQuarter3Date              : string;
    wagesQuarter4Date              : string;
    wagesQuarter1Amount            : string;
    wagesQuarter2Amount            : string;
    wagesQuarter3Amount            : string;
    wagesQuarter4Amount            : string;
    totalWagesForEmployee          : string;
    totalWagesForAllEmployees      : string;
    claimantWeeklyBenefitAmount    : string;
    benefitChargeableReserveAccount: string;
    formCode                       : string;
    createdBy                      : string;
    modifiedBy                     : string;
    createdOn                      : string;
    modifiedOn                     : string;
    claimId                        : number;
}
